### ISSUE TITLE
Recursion when ShowPlayerDialog calls in OnDialogResponse

### ISSUE THREAD

**Issue by NexiusTailer** [Gammix/Dialogs-Include#2]
Some time ago I found this problem in my alt_dialogs too. This happens when you calls the dialog when you reply to them. I noticed that the problem was solved in mSelection.

**Comment by Gammix** [comment]
I am pretty sure OnPlayerClickTextDraw causes that. Because when you CancelSelectTextDraw, onPlayerClickTextDraw is called with id INVALID_TEXT_DRAW; and our code when invalid td appears is to hide the dialog; which indirectly causes the bug. 

I had this issue solved in previous versions of dialogs.inc. I'll make a new repo in my new account with a good stable version, and i guess i'll rename the whole of it and change the syntax. There's no point in using dialogs standard and then breaking the string into parts. Like 3 times the work of mSelection.
